server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect